spring.application.name=quickstart
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=health,info


management.info.env.enabled=true
info.app.name = My Super Cool App
info.app.description = A crazy fun and mind blowing app , yahooo !!!!
info.app.version = 1.0.0


server.port = 1000
spring.datasource.url=jdbc:postgresql://localhost:5432/student
spring.datasource.username=postgres
spring.datasource.password=ominakavsar11
spring.jpa.show-sql=true
spring.main.banner-mode=off
logging.level.root =warn

logging.level.org.hibernate.SQL = debug
logging.level.org.hibernate.orm.jdbc.bind = trace


spring.jpa.hibernate.ddl-auto=update
